In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

In [4]:
df=pd.read_csv("housing.csv")

In [5]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

## Handling outliers

In [30]:
data=[10,12,12,13,13,14,12,14,13,19,90]
df_sample=pd.DataFrame(data,columns=['value']) # columns=['value'] giving column names as value

In [31]:
# CALCULATING ZSCORE
df_sample['Z_score'] = (
    df_sample['value'] - df_sample['value'].mean()
) / df_sample['value'].std()

In [32]:
df_sample

    value   Z_score
0      10 -0.437684
1      12 -0.351711
2      12 -0.351711
3      13 -0.308724
4      13 -0.308724
5      14 -0.265737
6      12 -0.351711
7      14 -0.265737
8      13 -0.308724
9      19 -0.050803
10     90  3.001264

In [33]:
outliers_z=df_sample[df_sample['Z_score'].abs() > 3]
outliers_z

    value   Z_score
10     90  3.001264

In [34]:
data=[10,12,12,13,13,14,12,14,13,19,90]
df_sample=pd.DataFrame(data,columns=['value']) # columns=['value'] giving column names as value

In [55]:
from sklearn.preprocessing import PowerTransformer
df_sample['log']=np.log(df_sample['value'])
df_sample['sqrt']=np.sqrt(df_sample['value'])
pt_yeojohnson=PowerTransformer(method='yeo-johnson')
df_sample['yeojohnson']=pt_yeojohnson.fit_transform(df_sample[['value']])

In [56]:
df_sample

    value       log      sqrt  yeojohnson
0      10  2.302585  3.162278   -1.878199
1      12  2.484907  3.464102   -0.557099
2      12  2.484907  3.464102   -0.557099
3      13  2.564949  3.605551   -0.115632
4      13  2.564949  3.605551   -0.115632
5      14  2.639057  3.741657    0.232733
6      12  2.484907  3.464102   -0.557099
7      14  2.639057  3.741657    0.232733
8      13  2.564949  3.605551   -0.115632
9      19  2.944439  4.358899    1.211874
10     90  4.499810  9.486833    2.219056